### PR TITLE
fixed bugs on the application flow

### LINKED ISSUE #445: [ Bug Report ] - LDN application Flow - cannot edit an already created issue
**Describe the bug**
Cannot Edit an already created issue
When I create an issue from here --> https://beta-verify.fil.org/ldn-application
then I leave the page and I get back to it later I have this:

Schermata 2022-05-19 alle 15 19 57

Issue title is missing and the regex is returning an error
**To Reproduce**
1. Go to '/ldn-application'
2. create an issue 
3. come back to the page later
4. open the issue previously created

**Expected behavior**
should allow the user to continue editing the issue

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
error: 
`Uncaught TypeError: Cannot read property 'type' of undefined
    at a.value (LdnApplication.tsx:167)
    at a.value (LdnApplication.tsx:85)
    at onClick (LdnApplication.tsx:405)
    at Object.c (react-dom.production.min.js:14)
    at h (react-dom.production.min.js:14)
    at react-dom.production.min.js:14
    at v (react-dom.production.min.js:15)
    at ot (react-dom.production.min.js:52)
    at it (react-dom.production.min.js:51)
    at ct (react-dom.production.min.js:52)
    at ht (react-dom.production.min.js:56)
    at R (react-dom.production.min.js:287)
    at F (react-dom.production.min.js:19)
    at Zt (react-dom.production.min.js:70)
    at $t (react-dom.production.min.js:69)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Bi (react-dom.production.min.js:122)
    at N (react-dom.production.min.js:287)
    at Jt (react-dom.production.min.js:68)
    at HTMLDocument.i (helpers.ts:99)
value @ LdnApplication.tsx:167
value @ LdnApplication.tsx:85
onClick @ LdnApplication.tsx:405
c @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonimo) @ react-dom.production.min.js:14
v @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
it @ react-dom.production.min.js:51
ct @ react-dom.production.min.js:52
ht @ react-dom.production.min.js:56
R @ react-dom.production.min.js:287
F @ react-dom.production.min.js:19
Zt @ react-dom.production.min.js:70
$t @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bi @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Jt @ react-dom.production.min.js:68
i @ helpers.ts:99`

### PR DESCRIPTION
**Pull request by huseyincansoylu**
close #445 #446 

Objective:

-  Fixed two bugs on the application flow.

### CODE REVIEW

File: src/pages/LdnApplication.tsx [hunk 1]
```diff
@@ -324,6 +335,10 @@ class LdnApplication extends Component<{}> {
     console.log('goToIssue--> TODO')
   }
 
+  draftOrSubmit() {
```
Comment (fabriziogianni7) [inline src/pages/LdnApplication.tsx:338]: what is this needed for?

File: src/pages/LdnApplication.tsx [hunk 2]
```diff
@@ -539,7 +547,7 @@ class LdnApplication extends Component<{}> {
                       <div className='otherInfoButtonContainer'>
                         <Button variant="contained" color="primary" onClick={() => this.prevStep()}>Back</Button>
                         <span style={{ marginRight: '10px' }}></span>
-                        <Button variant="contained" color="primary" onClick={() => this.updateIssueAndContinue()}>Submit Issue</Button>
+                        <Button variant="contained" color="primary" onClick={() => this.updateIssueAndContinue()}>{otherInfo.some(item => item.value === "") ? "Save Draft" : "Submit Issue"}</Button>
                       </div> :
                       <div className='otherInfoButtonContainer'>
                         <span style={{ marginRight: '10px' }}>The issue is successfully submitted!</span>
```
Comment (fabriziogianni7) [inline src/pages/LdnApplication.tsx:553]: the function goToIssue() is not existing anymore.
can you change this button to an <a> tag redirecting to the issue?
