### PR TITLE
Ref/api calls app

### LINKED ISSUE #622: [ Bug Report ] infinte api call
https://github.com/filecoin-project/notary-governance/issues/800

### PR DESCRIPTION
**Pull request by huseyincansoylu**
optimizing/refactoring both "rkh" and "notary view"

close #622 #624

### CODE REVIEW

File: src/components/OverviewApp/Notary.tsx [hunk 1]
```diff
@@ -14,17 +14,15 @@ import { BeatLoader } from "react-spinners";
...
+import { ldnParser } from "@keyko-io/filecoin-verifier-tools";
 
 
 type NotaryProps = {
   clients: any[];
-  searchString: string;
 };
 
-type CancelProposalData = {
+type CancelProposalDataType = {
```
Comment (fabriziogianni7) [inline src/components/OverviewApp/Notary.tsx:25]: you dont need to name it with "type" at the end

**Review by fabriziogianni7 — APPROVED** [review]
