### PR TITLE
Bug/search bar

### LINKED ISSUE #641: search box in the header is not working properly

### PR DESCRIPTION
**Pull request by huseyincansoylu**
close #641

### CODE REVIEW

File: src/components/OverviewApp/Notary/LargeRequestTable.tsx [hunk 1]
```diff
@@ -61,16 +63,36 @@ type LargeRequestTableProps = {
...
+                .map((item: any) => item.tx !== null ? item : { ...item, tx: "", })
+            setDataForLargeRequestTable(data)
+        }
+    }, [context.searchString, context.largeClientRequests])
+
+
     return (
         <div className="large-request-table" style={{ minHeight: "500px" }}>
+            {!context.ldnRequestsLoading && <p style={{ margin: "0.8rem  1.2rem", color: "#373D3F" }}>
+                * <i style={{ textDecoration: "underline", textUnderlineOffset: "4px" }}>You can look for specific deals querying by "Client", "Address" and "Audit Trail" fields using the search box.</i>
```
Comment (fabriziogianni7) [inline src/components/OverviewApp/Notary/LargeRequestTable.tsx:94]: maybe you cna change to
`Use the search box to search for issues, then  press enter or click on the lens`

**Review by fabriziogianni7 — CHANGES_REQUESTED** [review]
Looks good. the only problem is that you can query only for "Client", "Address" and "Audit Trail". maybe you can make the search bar work also with other fields, like datacap, msig or tx d

File: src/components/OverviewApp/Notary/LargeRequestTable.tsx (hunk 1 above)
Comment (huseyincansoylu) [reply src/components/OverviewApp/Notary/LargeRequestTable.tsx]: thanks i did the changes you asked for

**Review by fabriziogianni7 — APPROVED** [review]
